### ISSUE TITLE
Button resize

### ISSUE THREAD

**Issue by feedhopper** [cumany/obsidian-editing-toolbar#35]
Is it possible to set the size of the buttons? I find them a little small on my 42 inch monitor.

**Comment by cumany** [comment]
Because the toolbar supports custom svg icons, the button size may make some svg icons display abnormally. Here is a snippet you can refer to, you can modify the value inside to the right size.
```css
:is(#cMenuToolbarModalBar,#cMenuToolbarPopoverBar) svg{
height: 32px !important;
width: 32px !important;
max-width: 32px  !important;
max-height: 32px  !important;
}

```
